// pdfimport.h — reads existing PDF files so their pages can be merged into a
// document generated by pdfgen ([pdf=Site3.pdf] / [pdfgen=Site3.txt, include]).
//
// Supported input: PDF 1.x with classic xref tables AND modern files using
// cross-reference streams + object streams (both decoded via zlib, incl. the
// PNG-style predictors they typically use). Encrypted PDFs are rejected with
// a clear error. Page attributes inherited through the page tree (MediaBox,
// Resources, Rotate, CropBox) are resolved and inlined, and each imported
// page's full object closure is deep-copied and renumbered into the target.
#pragma once
#define PDFGEN_PDFIMPORT_API 1

#include <functional>
#include <memory>
#include <string>

namespace pdf {

class ImportedPdfImpl;

class ImportedPdf {
public:
  ImportedPdf();
  ~ImportedPdf();

  // Parses the file. On failure returns false and sets `err`.
  bool load(std::string bytes, std::string& err);
  int pageCount() const;

  // Copies page `index` (0-based) with its whole object closure into the
  // target document. `reserve()` allocates the next object number,
  // `fill(num, body)` provides the finished body for a reserved number
  // (body excludes "N 0 obj"/"endobj"). The page's /Parent is set to
  // `parentObjNum`. Returns the page's object number, or 0 on error.
  int copyPage(int index,
               const std::function<int()>& reserve,
               const std::function<void(int, std::string)>& fill,
               int parentObjNum, std::string& err);

private:
  std::unique_ptr<ImportedPdfImpl> impl_;
};

} // namespace pdf
